---

- import_tasks: raid.yml

- name: "установка пакета lvm"
  apt:
    name: "lvm2"
    state: "present"

#- name: edit lmv.conf
#  lineinfile:
#    path: /etc/lvm/lvm.conf
#    insertafter: '\# filter = \[ "a\|.*\|" \]'
#    line: 'filter = [ "a|/dev/sd.*[1-9]$|", "a|/dev/mapper/mpath*|", "a|/dev/nvme[0-9]n*|", "r|.*|" ]'

#- name: update initramfs
#  shell:
#    update-initramfs -c -k $(uname -r)

- name: "Создание раздела для wal на raid 1 размером 14GB"
  community.general.parted:
    device: "{{ item }}"
    number: 1
#    part_type: logical
    flags: [ lvm ]
    state: "{{ state }}"
    label: gpt
    part_start: 0%
    part_end: 14GiB
  loop:
    - /dev/md0

- name: "Создание раздела для db на raid 1 размером 2.9TB"
  community.general.parted:
    device: "{{ item }}"
    number: 2
    flags: [ lvm ]
    state: "{{ state }}"
    label: gpt
    part_start: 14GiB
    part_end: 2.9TiB
  loop:
    - /dev/md0

- name: "Create PV и VG wal vg disks /dev/md0"
  lvg:
    pvs:
      - /dev/md0p1
    state: "{{ state }}"
    vg: ceph-vg-wal
  tags: vg


- name: "Create LV db disks /dev/md0"
  lvg:
    pvs:
      - /dev/md0p2
    state: "{{ state }}"
    vg: ceph-vg-db
  tags: vg

#Создание LV для db
- name: Create a logical volume osd-db-lv1
  community.general.lvol:
    vg: ceph-vg-db
    lv: "{{ item }}"
    size: "288G"
    state: "{{ state }}"
    force: true
  loop:
    - "osd-db-lv0"
    - "osd-db-lv1"
    - "osd-db-lv2"
    - "osd-db-lv3"
    - "osd-db-lv4"
    - "osd-db-lv5"
    - "osd-db-lv6"
    - "osd-db-lv7"
    - "osd-db-lv8"
    - "osd-db-lv9"
    - "osd-db-lv10"
    - "osd-db-lv11"
  tags: db

#Создание LV для wal
- name: "Create a logical volume osd-wal-lv1"
  lvol:
    vg: ceph-vg-wal
    lv: "{{ item }}"
    size: "1G"
    state: "{{ state }}"
    force: true
  loop:
    - "osd-wal-lv0"
    - "osd-wal-lv1"
    - "osd-wal-lv2"
    - "osd-wal-lv3"
    - "osd-wal-lv4"
    - "osd-wal-lv5"
    - "osd-wal-lv6"
    - "osd-wal-lv7"
    - "osd-wal-lv8"
    - "osd-wal-lv9"
    - "osd-wal-lv10"
    - "osd-wal-lv11"
  tags: wal

#Имена дисков берутся из переменных
- name: "Создание PV и VG для HDD VGCreate ceph-vg-data-"
  lvg:
    pvs: "{{ mydrive }}"
    state: "{{ state }}"
    vg: "ceph-vg-data-{{ myindex }}"
  vars:
    myindex: "{{ item.0 }}"
    mydrive: "{{ item.1 }}"
  with_indexed_items: "{{ mydrives }}"


#Имена дисков берутся из переменных
- name: "Создание LV для HDD LVCreate ceph-vg-data-"
  lvol:
    vg: "ceph-vg-data-{{ myindex }}"
    lv: "osd-data-lv{{ myindex }}"
    size: "+100%FREE"
  vars:
    myindex: "{{ item.0 }}"

- name: "update initramfs"
  shell: update-initramfs -c -k $(uname -r)
